### ISSUE TITLE
Feature Request: Putting the box tilt within bounds

### ISSUE THREAD

**Issue by EfremBraun** [akohlmey/topotools#10]
Hi Axel,

For some pdb files, I'm finding that TopoTools outputs a LAMMPS data file with a tilt factor greater than half the distance of the parallel box length, giving a LAMMPS error unless one first sets "box tilt large". It's not really a bug since there's nothing wrong with the data file, but I figured it might be something to update for a future release.
(I'm not familiar with the TopoTools code; sorry I'm being lazy and putting in a feature request rather than looking at the code myself and putting in a pull request.)

I'm attaching an example input file and the TopoTools output file that's generated with the commands:
```
package require topotools
mol new FAU_Si_1_nozeolite_relaxed.pdb
topo writelammpsdata system.data atomic
```

[data.in.txt](https://github.com/akohlmey/topotools/files/1050798/data.in.txt)
[FAU_Si_1_nozeolite_relaxed.pdb.txt](https://github.com/akohlmey/topotools/files/1050797/FAU_Si_1_nozeolite_relaxed.pdb.txt)

**Comment by akohlmey** [comment]
The overall design philosophy of TopoTools is "you get out what you put in", and thus your proposed feature doesn't really belong into TopoTools. Manipulating properties related to simulation boxes and periodic boundaries is done in the PBCTools plugin of VMD. So if anywhere, a feature to recompute the box for a different tilt, especially one that is compatible with current PBC settings belongs there. Wrapping coordinates back into a given box, is handled there as well.
