### ISSUE TITLE
atoms order in impropers list in writelammpsdata

### ISSUE THREAD

**Issue by alessiodavidgit** [akohlmey/topotools#12]
I utilized topotools package to generate the topology from a coordinate set representing some polymer chains (PMMA) to equilibrate in the molten/amorphous phase. In these molecules there are sp2 Carbons (carbonyls within ester groups) that require an improper torsion angle in order to stay planar.

I use this piece of code to generate the topology:

(((writelammpsdata uses 'resid' to generate mol index)))
for {set i 0} {$i < 100} {incr i} {
     set list [atomselect top "residue $i"]
     $list set resid $i
}

topo retypebonds
topo guessangles
topo guessdihedrals
topo guessimpropers tolerance 30
topo writelammpsdata myfile.lammps

The bonds list is perfectly spotted by the code (angles and dihedrals as well) but when I run the the simulation with lammps the sp2 Carbons are not planar. Instead, they seem to adopt an sp3-like pyramidal geometry (like ammonia).

I have noticed that in the list of improper dihedrals generated by Topotools for the LAMMPS data file (INDEX TYPE I J K L, where I J K and L are the atoms involved in the dihedral) the C-sp2 atom at the centre is in the second position of the list (i.e., J).
However, from the LAMMPS manual page (http://lammps.sandia.gov/doc/improper_harmonic.html ) it seems that those atoms should be in the first position (i.e., I). I say this because of the sentence: "Normally, the bonds I-J, I-K, I-L would exist for an improper to be defined between the 4 atoms".

Indeed, I solved this problem by positioning the sp2 Carbon in the first entry in the impropers list. These atoms stay reasonably planar, as they are expected to do.

**Comment by jvermaas** [comment]
Weird. This is how I would have expected it too based on my experience with CHARMM. All you'd need to do is switch the order around on line 198 and 199 of topoimpropers.tcl

**Comment by akohlmey** [comment]
Fixed by merging PR #14
