### ISSUE TITLE
TopoTools::replicatemol

### ISSUE THREAD

**Issue by gandhiforbes** [akohlmey/topotools#16]
Dear Sir,

Tutorial-2, Step 2e: Hexane /  Cyclohexane 1:1 mixture, simulation box is filled with equal of hexane and cyclohexane molecules. 

How can i modify  mixedhexanetodata.tcl so that i can fill simulation box with unequal number of molecules?

Thanks,
Anand

**Comment by akohlmey** [comment]
that is a VMD not a topotools question, and most certainly not an issue with topotools itself.
