### ISSUE TITLE
README was not renamed in Makefile

### ISSUE THREAD

**Issue by sizmailov** [akohlmey/topotools#18]
`README` apparently was renamed to `README.md`, but makefile still references older name: 

```
Copying topotools 1.8 files to /usr/local/lib/vmd/plugins//noarch/tcl/topotools1.8
cp: cannot stat 'README': No such file or directory
```

**Comment by akohlmey** [comment]
@sizmailov Thanks for the bug report. This will be fixed now and I'll ship the updates for inclusion into VMD as well.
