### ISSUE TITLE
writepsf write psf without segname

### ISSUE THREAD

**Issue by shuxiansheng2** [akohlmey/topotools#20]
dear professor, could you improve this function with writing segment name using segname attribute in vmd ?

**Comment by akohlmey** [comment]
> dear professor, could you improve this function with writing segment name using segname attribute in vmd ?

a) this has **nothing** to do with the topotools plugin.
b) VMD can only write out information that you provide. If you read a molecule from a file format that does not provide a segname property, you have to add it later via VMD script commands. If you don't then you having it written is **your** fault, not something in VMD that needs correction.
