### ISSUE TITLE
gromacs error

### ISSUE THREAD

**Issue by S30194** [akohlmey/topotools#21]
I am getting an error while executing the ions.tpr using ions.mdp script. I am using chsrmm36-feb2021 forcefield. 
ERROR 1 [file topol.top, line 38]:
  Atomtype HB not found
kindly help

**Comment by jvermaas** [comment]
Alright, I'm slow to this. How did you make this system? I don't have nearly enough information to reproduce this.

**Comment by akohlmey** [comment]
No followups
