### ISSUE TITLE
guessdihedral issue with epoxy groups on graphene

### ISSUE THREAD

**Issue by Movaffaq** [akohlmey/topotools#22]
Dear Axel
I recently began to study graphene oxide in which I had epoxy groups (O bonded to two adjacent C). When I export data files for lammps, I noticed topotools gives O-C-C-O and C-O-O-C dihedrals with the same id for 1st and last species. I was using topo1.7.
Kind regards,
Movaffaq

**Comment by akohlmey** [comment]
This should be already fixed in topotools version 1.8. See commit 0bc3951f707420a2651b403ce8eddc6c7dfbaa57
