### ISSUE TITLE
topotools error 

### ISSUE THREAD

**Issue by MamtaMohan** [akohlmey/topotools#5]
Hello,

I want to use topotools 1.6 for topology conversion.

After download I untar the file and as instructed in install instructions, I copied directory topotools1.6/
in directory: /usr/local/lib/vmd/plugins/noarch/tcl

where topotools1.5/ is located.

To install topotools I followed following directions:
Installation
unpack the tar archive which will create a directory named topotools1.6, and move it next to the topotools1.5 directory from your existing VMD 1.9.2 installation. VMD should use the new version automatically at the next start. To uninstall, just remove the topotools1.6 directory.

While I am trying to call version 1.6 via command: package require topotools 1.6, however topotools1.5 is fine.

I am getting error: 
>Main< (mamta) 40 % package require topotools 1.5
1.5
>Main< (mamta) 41 % package require topotools 1.6
version conflict for package "topotools": have 1.5, need 1.6
>Main< (mamta) 42 % 

I would appreciate your help.

Mamta

**Comment by akohlmey** [comment]
This doesn't look like you restarted VMD after you installed the new topotools version. I just tried several variants of installing TopoTools into an existing VMD installation and they all worked as expected. The error has to be somewhere on your side.
