### ISSUE TITLE
TopoTools coverted .top error missing atomtype 

### ISSUE THREAD

**Issue by MamtaMohan** [akohlmey/topotools#6]
Hello,

I used TopoTools on a sample alanine.pdb file and generated a structure.top file.

grompp gives following error:
Program gmx grompp, VERSION 5.1.1
Source code file: /home/mamta/Gromacs/gromacs-5.1.1/src/gromacs/gmxpreprocess/toppush.c, line: 1353

Fatal error:
Atomtype NH3 not found
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors

I am listing sequence of commands I gave:
gmx editconf -f alanine.pdb -o newbox.gro -c -d 1.0 -bt cubic
cp structure.top topol.top
gmx solvate -cp newbox.gro -cs spc216.gro solv.gro -p topol.top 
gmx solvate -cs -cp newbox.gro -o  solv.gro -p topol.top 
less topol.top 
gmx grompp -f em.mdp -c solv.gro -p topol.top 
 
I am mailing files in mail to mail-id: akohlmey@gmail.com 

Mamta

**Comment by akohlmey** [comment]
There is not enough information here. How exactly did you generate alanine.psf and structure.top?

**Comment by MamtaMohan** [comment]
Dear Axel,

Thank you for your response.

Alanine.psf was generated via autopsf (VMD) then I generated structure.top via topotools 1.6 in tcl/tk console in VMD.

I have mailed all files to mail-id:  akohlmey@gmail.com as an attachment to to mail.

Mamta

**Comment by akohlmey** [comment]
That is all useless and doesn't tell me anything. I have to assume at this point, that you didn't use TopoTools correctly.

**Comment by akohlmey** [comment]
Let me clarify a little: before you can use TopoTools correctly to generate a Gromacs input for CHARMM, you need to have a correct PSF/PDB with a matching parameter files that works with NAMD.
Then you have to use TopoTools correctly to load and convert those files. For both steps, you will have to **convince** me, that you did those correctly, before I will even consider looking at your files. The files you provided and the detailed descriptions you gave, are only relevant, if I wanted to debug the **Gromacs** side of things, but that would not really be a TopoTools issue.

**Comment by MamtaMohan** [comment]
Dear Alex,

I am sorry I was away from my desk.

I followed all the steps correctly to generate file via autopsf and then .top file via TopoTools.

I do agree with you on every single account about debugging Gromacs issue is different from TopoTools.

To satisfy query I will another run and try to run the file in Gromacs.

If topology file created by Topotools again fails then I would think you might like to help me with Topotools issue.

Mamta

**Comment by MamtaMohan** [comment]
Dear Alex,

I run one more test.

Again I got an error:
Program gmx grompp, VERSION 5.1.1
Source code file: /home/mamta/Gromacs/gromacs-5.1.1/src/gromacs/gmxpreprocess/toppush.c, line: 1353

Fatal error:
Atomtype NH3 not found
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors

I took protein 1aki.pdb
I loaded the file in VMD and
generated .psf file via auto_psf
and generated .top file via TopoTools 1.6

In Gromacs I gave following commands:
gmx editconf -f 1aki.pdb -o newbox.gro -c -d 1.0 -bt cubic
gmx solvate -cs -cp newbox.gro -o solv.gro -p topol.top 
gmx grompp -f em.mdp -c solv.gro -p topol.top 

The same protein is used in gromacs tutorial and when I took the tutorial I was able to generate everything in Gromacs. So I would like to say Gromacs should not be the one causing error.

However I can be wrong.

For your convenience I am going to send you both directories at mail-id  akohlmey@gmail.com:
1 1aki.pdb processed via VMD and topotools 
2 Gromacs directory which has complete run.

Please let me know if I am missing something.

Mamta

**Comment by akohlmey** [comment]
This  is all pointless and not helping at all. If there is any problem, it has to happen **before**, but you are not providing **any** evidence, that you either generated a correct .psf file nor that you were using topotools correctly. I cannot help people that do not provide required information.

**Comment by jvermaas** [comment]
What was the line you used to generate the .top file? That would be the most helpful in figuring out what the problem might be. I suspect you did not provide a CHARMM parameter file to topotools when you generated the .top, since GROMACS is complaining about atomtype NH3, which would normally be the first atom on the N-terminus.

**Comment by MamtaMohan** [comment]
.top file was generated via TopoTools. I used following command in Tcl/Tk console

First I loaded 1aki_autopsf.psf and 1aki_autopsf.pdb in visualizer as new molecule
Opened Tcl/Tk console and gave following command: 
topo writegmxtop structure.top [list /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmtop1.1/top_all27_prot_lipid_na.inp]

**Comment by MamtaMohan** [comment]
.top file was generated via TopoTools. I used following command in Tcl/Tk console

First I loaded 1aki_autopsf.psf and 1aki_autopsf.pdb in visualizer as new molecule
Opened Tcl/Tk console and gave following command:
topo writegmxtop structure.top [list /usr/local/lib/vmd/plugins/noarch/tcl/readcharmmtop1.1/top_all27_prot_lipid_na.inp]


________________________________

**Comment by jvermaas** [comment]
You provided a topology file, not a parameter one. If you are set on using CHARMM27, you will need to find the appropriate parameter file (par_all27_prot_lipid_na.prm was the filename if I remember correctly, although most of the field has moved on to CHARMM36).

**Comment by MamtaMohan** [comment]
Thank you.

I will try that.

**Comment by MamtaMohan** [comment]
Dear Josh,
But I am still having issues with structure.top generated via TopoTools.
Latest issue is:
Fatal error:
No such moleculetype SOL
For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors

For parameter file as mentioned at NAMD tutorial site I used parameter file: par_all22_prot_cmap.inp.
structure.top was generated.

Command:
gmx grompp -f em.mdp -c solv.gro -p topol.top
gives error --- Fatal error: No such moleculetype SOL

It almost looks like water is not included.

I would appreciate your response.

Mamta

**Comment by jvermaas** [comment]
I wouldn't be too sure about that. The topol.top generated will have water. It just won't be called SOL. You probably are using that molecule type in your mdp file, which is why GROMACS rightly throws an error.

**Comment by MamtaMohan** [comment]
Dear Josh,

The issue with error -- Fatal error: No such moleculetype SOL

I was able to figure out. It is because system is protein + water system and .top file generated does not have solvent.
Gromacs command: gmx pdb2gmx -f 1AKI.pdb -o 1AKI_processed.gro -water spce
is executed first to build topology file which have solute, solvent, ion .itp files along with FF .itp file information and posre.itp file.

Structure.top generated via TopoTools does not carry this information and there is no posres.itp file.
So if I want to restrain some atoms in solute it is a problem for me, which I would need since my protein is labelled and I want to hold backbone still. 

For the time being if I overlook this, there is still a problem because when I execute command:
gmx grompp -f em.mdp -c solv.gro -p topol.top

It does not go through and gives me error -- Fatal error: Atomtype HB not found

Since 3lzm.pdb is just a protein in TopoTools to build .top file I used following parameter and topology files: par_all36_prot.prm, top_all36_prot.rtf

The error persists even though I added file: toppar_water_ions.str with the first two files.

I would appreciate your response.

Mamta

**Comment by jvermaas** [comment]
The tool does exactly what it says on the tin. It writes out a topology file based on what is loaded in VMD. If the structure in VMD doesn't have water, neither will the generated topology file. Did you regenerate the psf after using CHARMM36? The atomtypes changed between 27 and 36, which is the error you get, since the matching won't work.
