### ISSUE TITLE
Update residues

### ISSUE THREAD

**Issue by jonas-feldt** [akohlmey/topotools#8]
Dear Developers,

I'm using the TopoTools commands `clearbonds` and `addbonds` to correctly set the bonds for my system which works like a charm. However the definition of residues is not updated based on the new bonds.

I would like to use the residue information for atomselections or subsequent calls to PBCTools wrap function with the compound option.

I tried to set the residue information manually with the set command of atomselections. However I just get the message `data not modifiable`. Is there any possibility to update the residues with TopoTools?

Thank you for time,
Jonas

**Comment by jvermaas** [comment]
Are the resids the same? My recollection is that VMD checks for things to have the same resid in addition to being bonded. It might also require the atoms being consecutive. In any event, "mol reanalyze top" is the VMD command you want, since it reevaulates residue definitions.

**Comment by jonas-feldt** [comment]
Thanks a lot @jvermaas ! 'mol reanalyze' is exactly what I was looking for.

I had a number of molecules merged into a single residue because the distance based bond detection connected them all. So I set the correct bonds (= disconnected them) and hoped that it will also redefine the residues.
